pipeline {
    agent any
    stages {
        stage('colne') {
            steps {
                sh 'mkdir -p myprojects'
                sh 'rm -rf myprojects/*'            
                sh 'cd myprojects'
                sh 'git clone https://github.com/ZOUANI/walo.git'
            }
        }
        stage('build') {
                    steps {
                        sh 'cd myprojects/walo'
                        sh 'mvn package'
                    }
                }

        stage('run') {
                    steps {
                      sh 'cd myprojects/walo'
                      sh 'java -jar walo*.jar'
                    }
                }
            }
    
}
